# Generated by Django 2.1.4 on 2018-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='path',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
