# Generated by Django 2.1.4 on 2018-12-24 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
